package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import com.codeborne.selenide.SelenideElement;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;



public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Aperto main page test")
    void generatedTest() {
        step("Open 'https://www.aperto.com/aperto/de'", () -> {
            open("https://www.aperto.com/aperto/de");
            SelenideElement toggle = $(".toggle-main-nav .inner");
            SelenideElement work = $("nav.b-nav.is-main-nav ul:nth-child(2) li:nth-child(3) a");
            SelenideElement accept = $("#uc-btn-accept-banner");
            accept.click();
            toggle.click();
            work.shouldHave(Condition.text("Work"));
            work.click();

        });

        step("Set", () -> {
            step("// todo: just add selenium action");
        });

        step("Set", () -> {
            step("// todo: just add selenium action");
        });

        step("Submit", () -> {
            step("// todo: just add selenium action");
        });
    }
    @Test
    void test1() {
        open("https://www.aperto.com/aperto/de");
        $("#uc-btn-accept-banner").click();
        $(".headline", 2).click();
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.aperto.com/aperto/de'", () ->
            open("https://www.aperto.com/aperto/de"));

        step("Page title should have text 'Aperto | A Leading Digital Agency'", () -> {
            String expectedTitle = "Aperto | A Leading Digital Agency";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.aperto.com/aperto/de'", () ->
            open("https://www.aperto.com/aperto/de"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}